# Copyright (c) 2012-2018 Sebastien Rombauts (sebastien.rombauts@gmail.com)

# build format
version: "{build}"

# scripts that run after cloning repository
install:
 - git submodule update --init googletest
 - Set-ExecutionPolicy RemoteSigned -scope CurrentUser
 - iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
 - scoop bucket add wio https://github.com/wio/wio-bucket.git
 - scoop install wio

# configurations to add to build matrix
# TODO: VS2010->VS2015 and Win32/Win64 (see https://github.com/google/googletest/blob/master/appveyor.yml)
# TODO: MinGW Makefiles and MSYS Makefiles
configuration:
  - Debug
# - Release # CMake can only build the default configuration on Visual Studio
 
# scripts to run before build
before_build:
  - wio install

# build examples, and run tests (ie make & make test)
build_script:
  - wio build -all
